### ISSUE TITLE
模型加载

### ISSUE THREAD

**Issue by song201216** [tsingqguo/misf#1]
您好，当测试的时候，预训练是怎么加载的呢？谢谢

**Comment by Li-Xiaoguang** [comment]
Load the pre-trained model:
1. Download the pre-trained model and put that under checkpoints
2. Change "MODEL_LOAD: InpaintingModel" in checkpoints/config.yml

**Comment by CXNing** [comment]
I got only gray output. Maybe to test pre-trained model, we also need the pre-trained 251000_KPN_bs_8_opt？

**Comment by gordinmitya** [comment]
@Li-Xiaoguang @CXNing faced the same issue, have you solved somehow?

**Comment by Li-Xiaoguang** [comment]
Hello,
It looks like you do not load the pre-trained model successfully. It will print "Loading InpaintingModel generator..." when the pre-trained model is loaded. 

If you want to test the face inpainting, please follow the following:
1. make sure you have downloaded the "celebA_InpaintingModel_dis.pth" and "celebA_InpaintingModel_gen.pth" and put that inside the checkpoints folder
2. change "MODEL_LOAD: celebA_InpaintingModel" in checkpoints/config.yml

**Comment by CXNing** [comment]
I solved it by modify the path directly in https://github.com/tsingqguo/misf/blob/e9f6ad0eb47552f0c16e6e205bf9aa767ddabb4b/src/models.py#L25

**Comment by tsingqguo** [comment]
The issue has been solved. Thanks.
