### ISSUE TITLE
关于网络的输出问题

### ISSUE THREAD

**Issue by xinzi2018** [tsingqguo/misf#13]
请问网络中的输出是整张图片还是单纯mask擦除部分的预测结果？
我在阅读计算损失函数部分代码的时候觉得输出应该是整张图片，但是看代码在可视化的时候有一个计算outputs_merged的过程，并且在计算指标的时候也是通过outputs_merged和gt进行计算的。

**Comment by yunbingbing** [comment]
> 请问网络中的输出是整张图片还是单纯mask擦除部分的预测结果？ 我在阅读计算损失函数部分代码的时候觉得输出应该是整张图片，但是看代码在可视化的时候有一个计算outputs_merged的过程，并且在计算指标的时候也是通过outputs_merged和gt进行计算的。

你好！请问你复现出来了吗？代码的指标是否跟论文差不多呢？

**Comment by xinzi2018** [comment]
还没有呢，我现在的结果还有问题

**Comment by superlittl** [comment]
我也在复现这篇论文，可否讨论下吗

**Comment by yunbingbing** [comment]
> 我也在复现这篇论文，可否讨论下吗
欢迎加我qq 3559640395

**Comment by Li-Xiaoguang** [comment]
非常感谢大家对我们的工作感兴趣。

网络的输出是 整张图片。 我们follow 之前的工作，在计算指标的时候 把生成的masked area 和 gt 中 非 masked area 合并。

大家复现论文结果的时候，遇到什么问题请留言，我会尽快回复。

**Comment by Charlieww** [comment]
请问环境的具体配置信息可以提供吗？比如PyTorch具体版本，本地计算出的指标和论文指标有一些出入，感谢。

**Comment by shaoyingjie66** [comment]
> 请问环境的具体配置信息可以提供吗？比如PyTorch具体版本，本地计算出的指标和论文指标有一些出入，感谢。

我复现后的psnr指标也比论文搞3个点左右，不知道哪里出问题了

**Comment by Li-Xiaoguang** [comment]
在train 的时候我们使用 pytorch1.0。 测试的时候 pytorch 1.0 和 pytorch 1.7.0 都可以复现测试结果。 请问 你是在哪个数据集上测试的？ 
在Places2 数据集上，我们随机选取 3万个图片测试。
在 CelabA 数据集上，我们用标准测试集。

测试用的mask，根据 mask的大小 分为三个等级 0-20%， 20-40%， 40-60%， 可以从下面link下载
https://drive.google.com/file/d/1cuw8QGfiop9b4K7yo5wPgPqXBIHjS6MI/view?usp=sharing

**Comment by shaoyingjie66** [comment]
> 在train 的时候我们使用 pytorch1.0。 测试的时候 pytorch 1.0 和 pytorch 1.7.0 都可以复现测试结果。 请问 你是在哪个数据集上测试的？ 在Places2 数据集上，我们随机选取 3万个图片测试。 在 CelabA 数据集上，我们用标准测试集。
> 
> 测试用的mask，根据 mask的大小 分为三个等级 0-20%， 20-40%， 40-60%， 可以从下面link下载 https://drive.google.com/file/d/1cuw8QGfiop9b4K7yo5wPgPqXBIHjS6MI/view?usp=sharing

您好 非常感谢您的回复！
我是在celeba划分好的测试集，以及您提供的mask_divide掩码集和celebA_InpaintingModel训练模型，pytorch1.7.0 cuda11上测试的。但是在 0-20%的测试结果比论文中的结果要高3个点左右，如下所示
edge_psnr_ave:37.295202529751 edge_ssim_ave:0.9758879160218611 l1_ave:0.003544746127828567 lpips:0.027104865559111787

**Comment by Li-Xiaoguang** [comment]
> > 在train 的时候我们使用 pytorch1.0。 测试的时候 pytorch 1.0 和 pytorch 1.7.0 都可以复现测试结果。 请问 你是在哪个数据集上测试的？ 在Places2 数据集上，我们随机选取 3万个图片测试。 在 CelabA 数据集上，我们用标准测试集。
> > 测试用的mask，根据 mask的大小 分为三个等级 0-20%， 20-40%， 40-60%， 可以从下面link下载 https://drive.google.com/file/d/1cuw8QGfiop9b4K7yo5wPgPqXBIHjS6MI/view?usp=sharing
> 
> 您好 非常感谢您的回复！ 我是在celeba划分好的测试集，以及您提供的mask_divide掩码集和celebA_InpaintingModel训练模型，pytorch1.7.0 cuda11上测试的。但是在 0-20%的测试结果比论文中的结果要高3个点左右，如下所示 edge_psnr_ave:37.295202529751 edge_ssim_ave:0.9758879160218611 l1_ave:0.003544746127828567 lpips:0.027104865559111787

你有修改过 dataload 那块的代码么，比如 “ mask = (mask > self.mask_threshold).astype(np.uint8) * 255 ” 。 不同的 mask_threshold 会导致 测试结果不同

**Comment by shaoyingjie66** [comment]
> > > 在train 的时候我们使用 pytorch1.0。 测试的时候 pytorch 1.0 和 pytorch 1.7.0 都可以复现测试结果。 请问 你是在哪个数据集上测试的？ 在Places2 数据集上，我们随机选取 3万个图片测试。 在 CelabA 数据集上，我们用标准测试集。
> > > 测试用的mask，根据 mask的大小 分为三个等级 0-20%， 20-40%， 40-60%， 可以从下面link下载 https://drive.google.com/file/d/1cuw8QGfiop9b4K7yo5wPgPqXBIHjS6MI/view?usp=sharing
> > 
> > 
> > 您好 非常感谢您的回复！ 我是在celeba划分好的测试集，以及您提供的mask_divide掩码集和celebA_InpaintingModel训练模型，pytorch1.7.0 cuda11上测试的。但是在 0-20%的测试结果比论文中的结果要高3个点左右，如下所示 edge_psnr_ave:37.295202529751 edge_ssim_ave:0.9758879160218611 l1_ave:0.003544746127828567 lpips:0.027104865559111787
> 
> 你有修改过 dataload 那块的代码么，比如 “ mask = (mask > self.mask_threshold).astype(np.uint8) * 255 ” 。 不同的 mask_threshold 会导致 测试结果不同

没有修改，使用的是config文件提供的默认参数。我觉得是因为pytorch1.1.0版本训练出来的结果会偏低

**Comment by Hgy12345** [comment]
我也在复现这篇论文，可否讨论下吗
欢迎加我qq/微信 2252650665
