### ISSUE TITLE
环境配置问题？

### ISSUE THREAD

**Issue by shaoyingjie66** [tsingqguo/misf#14]
您好！我在运行时产生了多个与包版本相关的问题，版本冲突。您是否可以详细写下具体的包版本，比如python,pytorch,cuda。

**Comment by Li-Xiaoguang** [comment]
您好，
非常感谢对我们的工作感兴趣。 实验中，我们使用 python 3.7， cuda 10， pytorch 1.0 以上版本都可以（使用 pytorch 1.0 和 pytorch 1.7.0  都可以复现测试结果 ）
