### ISSUE TITLE
训练的list文件

### ISSUE THREAD

**Issue by LYL-hub-source** [tsingqguo/misf#15]
请问data_list.py生成的 .txt文件是真实图像和纯掩码图像，还是带有掩码的图像和纯掩码的图像呢

**Comment by Li-Xiaoguang** [comment]
data_list.py 只是负责扫描 指定文件下的所有 image 并生成 每个image 对应的 绝对路径。 在dataload 中加载数据的时候，根据生成的路径直接读取图片。

**Comment by LYL-hub-source** [comment]
好的感谢大佬。
