### ISSUE TITLE
log

### ISSUE THREAD

**Issue by LYL-hub-source** [tsingqguo/misf#21]
Hello, may I ask if there is no log program

**Comment by Li-Xiaoguang** [comment]
I am confused about the question, could you make it clear, please?

**Comment by LYL-hub-source** [comment]
Hi, I would like to ask if there is any saving in the program about the training log files (losses as well as evaluation metrics)

**Comment by Li-Xiaoguang** [comment]
We only print the log in the code. When running the Python file, you can write the log into a file by the Linux command ">>".
