### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Destinyrhx** [tsingqguo/misf#22]
请问训练时出现这种情况该如何解决呢？请您百忙之中能够抽空解答，不胜感激！

![1](https://github.com/tsingqguo/misf/assets/134023967/8f958d11-81b7-4106-922b-fcb3afa93c16)

**Comment by Li-Xiaoguang** [comment]
Hello, this warning will not affect the training and evaluation, just disregard that.

**Comment by Destinyrhx** [comment]
Thank you for your reply. I have increased the maximum number of iterations and can now run normally. Would an increase in the maximum number of iterations affect the training effect?

**Comment by Li-Xiaoguang** [comment]
Increasing the maximum number of iterations will not affect the final result too much. Based on my experience, you may get a similar or slightly better result when you train the model for a longer time.

**Comment by 7423cg** [comment]
> 请问训练时出现这种情况该如何解决呢？请您百忙之中能够抽空解答，不胜感激！
> 
> ![1](https://github.com/tsingqguo/misf/assets/134023967/8f958d11-81b7-4106-922b-fcb3afa93c16)
你好，请问应该怎样正确的分割数据集呢？
