### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by yumengWang112** [tsingqguo/misf#29]
I download the pretrained model and test the model on celeba. But i got some error result images
![image](https://github.com/tsingqguo/misf/assets/79405379/211bb367-e068-4643-8bf2-19f0022e9647)
![image](https://github.com/tsingqguo/misf/assets/79405379/c6cef7cb-ba81-4e3b-95ab-bfacb6c12ede)

 the pre1 and pre2 images show like this
I wonder is there something i missed?

**Comment by PatrickLee02** [comment]
Have u solved it？I meet the same error.

**Comment by Li-Xiaoguang** [comment]
It looks like you did not load the pre-trained weight successfully. Please refer [here](https://github.com/tsingqguo/misf/issues/1)
