### ISSUE TITLE
About requirements.txt !

### ISSUE THREAD

**Issue by chanwo0kim** [tsingqguo/misf#3]
Hi!

First of all, congratulations on your successful work.

I am interested in this work and want to run the testing code, but requirements.txt was uploaded empty.

So, can I get the environment information or requirements.txt(or yaml) about this code?

Thank you!

**Comment by Li-Xiaoguang** [comment]
Hello,
Thanks for your interest in our work. I have updated the requirements.txt. By the way, you need to install python version >=3.0 and Pytorch version >= 1.0
