### ISSUE TITLE
Metrics 

### ISSUE THREAD

**Issue by JcccKing** [tsingqguo/misf#4]
您好，首先您论文非常不错，最近我研究方向和您很相关。我想请问您的指标都是在256分辨率测试的吗，壁画有没有丢进模型去训练，我尝试运行壁画原分辨率，出现像素不一致问题。是否是您KPN模块出现问题。
谢谢，祝科研顺利！

**Comment by Li-Xiaoguang** [comment]
感谢您对我们的工作感兴趣。所有输入到模型的图片 都需要 先crop 和 resize 到 256*256. 壁画的分辨率不统一，需要 crop 和 resize 后才能进入模型。

**Comment by JcccKing** [comment]
ok. 很感谢.
