### ISSUE TITLE
Test is not working

### ISSUE THREAD

**Issue by vsingh1998** [tsingqguo/misf#6]
Hello, I am facing an issue while testing your algorithm on a test image. I just put one image in the test folder and the corresponding masks according to the directory structure defined. I am getting this error:
![Screenshot from 2022-06-25 20-30-51](https://user-images.githubusercontent.com/25503951/175786226-9827bfbd-b0a9-467c-8594-056619ad7d36.png)
Looking forward to your response.
Thank you for your work.

**Comment by Li-Xiaoguang** [comment]
Hello,

Thanks for your interest in our work. Before testing, you need to generate the corresponding image list by this python file: /data/data_list.py. 

Then change the file path in checkpoints/config.yml.

Please let me know if you have any questions.
