### ISSUE TITLE
关于边缘

### ISSUE THREAD

**Issue by mmyjjl1009** [tsingqguo/misf#7]
您好，在看您的代码时发现里面还保留有EdgeCon的 边缘预测模型，但实际上在您的代码中其实并不包含对边缘的使用对吗？也就是不需要先预测边缘再修补图像。

**Comment by Li-Xiaoguang** [comment]
是的，我们的 论文 引用了 EdgeCon 和 参考了其部分代码。在我们的论文中没有用到edge信息，所以不需要对edge的预测和补全。
